create table if not exists public.otworker_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  username text not null unique,
  role text not null default 'USER',
  selected_month text not null,
  employee jsonb not null default '{}'::jsonb,
  active_timer jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.otworker_profiles
alter column auth_user_id drop not null;

alter table public.otworker_profiles
add column if not exists role text not null default 'USER';

update public.otworker_profiles
set role = 'USER'
where role is null or role not in ('USER', 'ADMIN');

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'otworker_profiles_role_check'
      and conrelid = 'public.otworker_profiles'::regclass
  ) then
    alter table public.otworker_profiles
    add constraint otworker_profiles_role_check
    check (role in ('USER', 'ADMIN'));
  end if;
end;
$$;

create table if not exists public.otworker_entries (
  id text primary key,
  profile_id bigint not null references public.otworker_profiles(id) on delete cascade,
  auth_user_id uuid,
  entry_date date not null,
  start_time text not null,
  end_time text not null,
  note text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists otworker_entries_profile_id_entry_date_created_at_idx
on public.otworker_entries (profile_id, entry_date, created_at);

create or replace function public.set_otworker_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists otworker_profiles_set_updated_at on public.otworker_profiles;

create trigger otworker_profiles_set_updated_at
before update on public.otworker_profiles
for each row
execute function public.set_otworker_updated_at();

drop trigger if exists otworker_entries_set_updated_at on public.otworker_entries;

create trigger otworker_entries_set_updated_at
before update on public.otworker_entries
for each row
execute function public.set_otworker_updated_at();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'otworker_profiles'
      and column_name = 'entries'
  ) then
    insert into public.otworker_entries (
      id,
      profile_id,
      auth_user_id,
      entry_date,
      start_time,
      end_time,
      note,
      created_at,
      updated_at
    )
    select
      coalesce(nullif(entry.item->>'id', ''), 'legacy-' || profile.id || '-' || entry.ordinality),
      profile.id,
      profile.auth_user_id,
      (entry.item->>'date')::date,
      coalesce(entry.item->>'startTime', '00:00'),
      coalesce(entry.item->>'endTime', '00:00'),
      coalesce(entry.item->>'note', ''),
      coalesce(
        profile.created_at + (((entry.ordinality - 1)::text || ' seconds')::interval),
        timezone('utc', now())
      ),
      coalesce(profile.updated_at, timezone('utc', now()))
    from public.otworker_profiles profile
    cross join lateral jsonb_array_elements(
      coalesce(profile.entries, '[]'::jsonb)
    ) with ordinality as entry(item, ordinality)
    on conflict (id) do nothing;

    update public.otworker_profiles
    set entries = '[]'::jsonb
    where entries is distinct from '[]'::jsonb;
  end if;
end;
$$;

alter table public.otworker_profiles drop column if exists entries;

alter table public.otworker_profiles enable row level security;
alter table public.otworker_entries enable row level security;

create or replace function public.is_otworker_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.otworker_profiles
    where auth_user_id = auth.uid()
      and role = 'ADMIN'
  );
$$;

grant select, insert, update, delete on public.otworker_profiles to authenticated;
grant usage, select on sequence public.otworker_profiles_id_seq to authenticated;
grant select, insert, update, delete on public.otworker_entries to authenticated;
grant execute on function public.is_otworker_admin() to authenticated;

drop policy if exists "Users can read own OTWORKER profile" on public.otworker_profiles;
create policy "Users can read own OTWORKER profile"
on public.otworker_profiles
for select
to authenticated
using (auth.uid() = auth_user_id or public.is_otworker_admin());

drop policy if exists "Users can insert own OTWORKER profile" on public.otworker_profiles;
create policy "Users can insert own OTWORKER profile"
on public.otworker_profiles
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can update own OTWORKER profile" on public.otworker_profiles;
create policy "Users can update own OTWORKER profile"
on public.otworker_profiles
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can delete own OTWORKER profile" on public.otworker_profiles;
create policy "Users can delete own OTWORKER profile"
on public.otworker_profiles
for delete
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "Users can read own OTWORKER entries" on public.otworker_entries;
create policy "Users can read own OTWORKER entries"
on public.otworker_entries
for select
to authenticated
using (auth.uid() = auth_user_id or public.is_otworker_admin());

drop policy if exists "Users can insert own OTWORKER entries" on public.otworker_entries;
create policy "Users can insert own OTWORKER entries"
on public.otworker_entries
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can update own OTWORKER entries" on public.otworker_entries;
create policy "Users can update own OTWORKER entries"
on public.otworker_entries
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can delete own OTWORKER entries" on public.otworker_entries;
create policy "Users can delete own OTWORKER entries"
on public.otworker_entries
for delete
to authenticated
using (auth.uid() = auth_user_id);
