create table if not exists public.otworker_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  username text not null unique,
  selected_month text not null,
  employee jsonb not null default '{}'::jsonb,
  active_timer jsonb,
  entries jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_otworker_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists otworker_profiles_set_updated_at on public.otworker_profiles;

create trigger otworker_profiles_set_updated_at
before update on public.otworker_profiles
for each row
execute function public.set_otworker_profiles_updated_at();

alter table public.otworker_profiles enable row level security;

grant select, insert, update, delete on public.otworker_profiles to authenticated;
grant usage, select on sequence public.otworker_profiles_id_seq to authenticated;

drop policy if exists "Users can read own OTWORKER profile" on public.otworker_profiles;
create policy "Users can read own OTWORKER profile"
on public.otworker_profiles
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "Users can insert own OTWORKER profile" on public.otworker_profiles;
create policy "Users can insert own OTWORKER profile"
on public.otworker_profiles
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can update own OTWORKER profile" on public.otworker_profiles;
create policy "Users can update own OTWORKER profile"
on public.otworker_profiles
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "Users can delete own OTWORKER profile" on public.otworker_profiles;
create policy "Users can delete own OTWORKER profile"
on public.otworker_profiles
for delete
to authenticated
using (auth.uid() = auth_user_id);
